# coding: utf-8

"""
    EDUWS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.1
    Contact: info@er76.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dict_put_api import DictPutApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDictPutApi(unittest.TestCase):
    """DictPutApi unit test stubs"""

    def setUp(self):
        self.api = DictPutApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dict_put(self):
        """Test case for dict_put

        Обновляет данные справочника  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
