# coding: utf-8

"""
    EDUWS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.1
    Contact: info@er76.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger client
from swagger client.models.count_group import CountGroup  # noqa: E501
from swagger client.rest import ApiException


class TestCountGroup(unittest.TestCase):
    """CountGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountGroup(self):
        """Test CountGroup"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger client.models.count_group.CountGroup()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
