# coding: utf-8

"""
    EDUWS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.1
    Contact: info@er76.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger client
from swagger client.api.xml_api import XmlApi  # noqa: E501
from swagger client.rest import ApiException


class TestXmlApi(unittest.TestCase):
    """XmlApi unit test stubs"""

    def setUp(self):
        self.api = XmlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_xml_send(self):
        """Test case for xml_send

        Ставит XML в очередь для последующей отправки в СМЭВ3  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
