# coding: utf-8

"""
    EDUWS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.1
    Contact: info@er76.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger client
from swagger client.api.dict_api import DictApi  # noqa: E501
from swagger client.rest import ApiException


class TestDictApi(unittest.TestCase):
    """DictApi unit test stubs"""

    def setUp(self):
        self.api = DictApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_dict(self):
        """Test case for dict

        Возвращает данные справочника  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
