# coding: utf-8

# flake8: noqa

"""
    EDUWS API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.3.1
    Contact: info@er76.ru
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import apis into sdk package
from swagger-client.api.appl_api import ApplApi
from swagger-client.api.dict_api import DictApi
from swagger-client.api.typeinfo_api import TypeinfoApi
from swagger-client.api.xml_api import XmlApi
# import ApiClient
from swagger-client.api_client import ApiClient
from swagger-client.configuration import Configuration
# import models into sdk package
from swagger-client.models.count_group import CountGroup
from swagger-client.models.count_query import CountQuery
from swagger-client.models.count_result import CountResult
from swagger-client.models.count_status import CountStatus
from swagger-client.models.dict_result import DictResult
from swagger-client.models.document import Document
from swagger-client.models.document_column import DocumentColumn
from swagger-client.models.document_field import DocumentField
from swagger-client.models.h_column import HColumn
from swagger-client.models.header import Header
from swagger-client.models.history_status import HistoryStatus
from swagger-client.models.one_of_document_field_value import OneOfDocumentFieldValue
from swagger-client.models.operation_result import OperationResult
from swagger-client.models.r_column import RColumn
from swagger-client.models.row import Row
from swagger-client.models.search_form import SearchForm
from swagger-client.models.search_form_field import SearchFormField
from swagger-client.models.search_query import SearchQuery
from swagger-client.models.search_result import SearchResult
from swagger-client.models.search_result_pagination import SearchResultPagination
from swagger-client.models.term_field import TermField
from swagger-client.models.update_status import UpdateStatus
from swagger-client.models.xml_send_body import XmlSendBody
